-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-02 09:19:17 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE book (
    book_id       INTEGER NOT NULL,
    book_name     VARCHAR2(15) NOT NULL,
    author_name   VARCHAR2(15)
);

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( book_id );

CREATE TABLE partition (
    pat_id   INTEGER NOT NULL,
    title    VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
     NOT NULL
);

ALTER TABLE partition ADD CONSTRAINT partition_pk PRIMARY KEY ( pat_id );

CREATE TABLE transaction (
    trans_id           INTEGER NOT NULL,
    date_time          DATE NOT NULL,
    book_book_id       INTEGER NOT NULL,
    partition_pat_id   INTEGER NOT NULL
);

ALTER TABLE transaction
    ADD CONSTRAINT transaction_pk PRIMARY KEY ( trans_id,
                                                book_book_id,
                                                partition_pat_id );

ALTER TABLE transaction
    ADD CONSTRAINT transaction_book_fk FOREIGN KEY ( book_book_id )
        REFERENCES book ( book_id );

ALTER TABLE transaction
    ADD CONSTRAINT transaction_partition_fk FOREIGN KEY ( partition_pat_id )
        REFERENCES partition ( pat_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
